name: FuckMan
version: '${project.version}'
main: r4mblesplugins.fuckman.FuckMan
authors: [ R4mBLe_ ]
description: Fuck your friends
commands:
  fuck:
    aliases: [fuck, fuckman]
  deny:
    aliases: [deny]

permissions:
  fuck:
    default: true
